# H2 Database Connection (File-based to persist data)
spring.datasource.url=jdbc:h2:file:./data/agriconnect_db;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# H2 Console (available at /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mail SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=gouravajjulasaisrikar@gmail.com
spring.mail.password=avom kvmi nawz qtjz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true